name: todoapp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5

  shared_preferences: ^2.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: false
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    theme_color: "#ffffff"
  macos:
    generate: true
    image_path: "assets/icons/icon.png"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
  linux:
    generate: true
    image_path: "assets/icons/icon.png"
  adaptive_icon_background: null
  adaptive_icon_foreground: "assets/icons/icon.png"
